USE DATABASE DEMO_DATABASE;

--1.create table and add primary key 
CREATE OR REPLACE TABLE "NG_SALES_DATA"
(
order_id VARCHAR (50)primary key,
 order_date VARCHAR(50),
 ship_date	VARCHAR(50),
 ship_mode	VARCHAR (50),
 customer_name	VARCHAR(50),
 segment	VARCHAR (50),
 state	VARCHAR (50),
 country CHAR(50),
 market	CHAR(50),
 region	VARCHAR(50),
 product_id	STRING,
 category	VARCHAR(50),
 sub_category	VARCHAR(50),
 product_name string,
 sales	INT,
 quantity	INT,
 discount	VARCHAR(50),
 profit	VARCHAR(50),
 shipping_cost	VARCHAR(50),
 order_priority	VARCHAR(50),
 year INT
);
DESCRIBE TABLE NG_SALES_DATA;

SELECT* FROM NG_SALES_DATA;


---2. CHECK THE ORDER DATE AND SHIP DATE TYPE AND THINK IN WHICH DATA TYPE YOU HAVE TO CHANGE

SELECT TRY_TO_DATE(ORDER_DATE, 'MM-DD-YYYY')FROM NG_SALES_DATA;

ALTER TABLE NG_SALES_DATA
ADD COLUMN ORDER_DATE_NEW  DATE;

UPDATE NG_SALES_DATA
SET ORDER_DATE_NEW = TRY_TO_DATE(ORDER_DATE, 'MM-DD-YYYY');

---SHIP DATE TYPE
SELECT TRY_TO_DATE (SHIP_DATE,'MM-DD-YYYY') FROM NG_sALES_DATA;

ALTER TABLE NG_SALES_DATA
ADD COLUMN SHIP_DATE_NEW DATE;

UPDATE NG_sALES_DATA
SET SHIP_DATE_NEW = TRY_TO_DATE(SHIP_DATE,'MM-DD-YYYY');


----3. EXTACT THE LAST NUMBER AFTER THE - AND CREATE OTHER COLUMN AND UPDATE IT.

ALTER TABLE NG_SALES_DATA 
ADD COLUMN ORDER_ID_NEW VARCHAR(255);

UPDATE NG_SALES_DATA 
SET ORDER_ID_NEW = (strtok(ORDER_ID, '-',3));


---4.FLAG ,IF DISCOUNT IS GREATER THEN 0 THEN  YES ELSE FALSE AND PUT IT IN NEW COLUMN FRO EVERY ORDER ID
SELECT DISTINCT DISCOUNT FROM NG_SALES_DATA;

ALTER TABLE NG_SALES_DATA 
ADD COLUMN VALID_DISCOUNT VARCHAR(255);

UPDATE NG_SALES_DATA 
SET VALID_DISCOUNT = (CASE WHEN DISCOUNT > '0' THEN 'YES'
ELSE 'FALSE'
END)

---5.FIND OUT THE FINAL PROFIT AND PUT IT IN COLUMN FOR EVERY ORDER ID.

ALTER TABLE NG_SALES_DATA 
ADD COLUMN FINAL_PROFIT VARCHAR(255);

SELECT SUM (PROFIT) FROM NG_SALES_DATA AS OVERALL_PROFIT
GROUP BY ORDER_ID;

---6.FIND OUT HOW MUCH DAYS TAKEN FOR EACH ORDER TO PROCESS FOR THE SHIPMENT FOR EVERY ORDER ID. 
ALTER TABLE NG_SALES_DATA 
ADD COLUMN DAYS_TAKEN_TO_PROCESS_TO_SHIP INT;

UPDATE NG_SALES_DATA 
SET DAYS_TAKEN_TO_PROCESS_TO_SHIP = (DATEDIFF('DAYS',ORDER_DATE_NEW,SHIP_DATE_NEW));

---7. FLAG THE PROCESS DAY AS BY RATING IF IT TAKES LESS OR EQUAL 3  DAYS MAKE 5,LESS OR EQUAL THAN 6 DAYS BUT MORE THAN 3 MAKE 4,LESS THAN 10 BUT MORE THAN 6 MAKE 3,MORE THAN 10 MAKE IT 2 FOR EVERY ORDER ID.
SELECT*,
CASE WHEN   DAYS_TAKEN_TO_PROCESS_TO_SHIP <=3 THEN 5
     WHEN   DAYS_TAKEN_TO_PROCESS_TO_SHIP BETWEEN 4 AND 6 THEN 4
     WHEN   DAYS_TAKEN_TO_PROCESS_TO_SHIP BETWEEN 7 AND 10 THEN 3
     ELSE 2
     END AS RATING 
     FROM NG_SALES_DATA;


